### ISSUE TITLE
update renamed symbols

### ISSUE THREAD

**Issue by stevengj** [gridap/GridapGmsh.jl#29]
It looks like some of the functions need to be renamed to be consistent with https://github.com/gridap/Gridap.jl/pull/494

In particular, we are seeing an error with `get_cell_nodes` (using `Gridap#master` and `GridapGmsh#update_to_Gridap_0.15`), which was renamed to `get_cell_node_ids`

**Comment by stevengj** [comment]
Update: renaming get_cell_nodes to get_cell_node_ids in `src/GmshDiscreteModels.jl` fixed the problem for us.

**Comment by fverdugo** [comment]
Hi @stevengj,

Yes, we have recently introduced this renaming in Gridap. Other two recent renamings:

`LebesgueMeasure` -> `Measure` 
`get_cell_id` -> `get_cell_to_bgcell`

**Comment by fverdugo** [comment]
I have pushed the changes to the `update_to_Gridap_0.15` branch in https://github.com/gridap/GridapGmsh.jl/commit/241d2862cae7cc580f400901176171a81fc307b7
