### ISSUE TITLE
loading msh file

### ISSUE THREAD

**Issue by edljk** [gridap/GridapGmsh.jl#30]
Thank you for all the work on `Gridap`!
I encounter a difficulty in loading a simple geometry from a gmsh file (_manually generated_..).
The file can be downloaded [here](https://www-ljk.imag.fr/membres/Edouard.Oudet/download/mydisk.msh).

I checked the mesh and the `boundary_1` labeling (a circle) with paraview and 
it looks ok but the instructions

```julia
 model = GmshDiscreteModel("mydisk.msh")
 V0 = TestFESpace(reffe = :Lagrangian, order = 1, valuetype = Float64, conformity = :H1, model = model,  dirichlet_tags = ["boundary_1",])
```
produces a `V0` structure with an enexpected `V0.ndirichlet == 0`..

**Comment by edljk** [comment]
I was not able to identify where does the problem come from in previous msh file.
By the way, I solved my original problem avoiding the use of gmsh. I was initially interested in generating a Gridap model starting from a  naive array representation of a mesh (points =  Array{Float64, 2}, elements = ) Array{Int64, 2}).
This is achieved by the following piece of code. Perhaps a simpler approach is already implemented.. ?
Thanks once again for this nice library.

```julia
# Input: points, elements and boundary elements: 
# p = np x dim Array{Float64, 2}
# T = nT x (dim + 1) Array{Int64, 2}
# Tb = nT x dim  Array{Int64, 2}

np, nT, dim = size(p, 1), size(T, 1), size(p, 2)
regions = [T, Tb]
regionsnames, regionsdims = ["domain", "boundary_1"], [dim, dim - 1]
# unstructured grid
nodes =  [Gridap.VectorValue{size(p, 2), Float64}(p[k, :]...) for k = 1:np]
cells = Gridap.Arrays.Table([T[k, :] for k = 1:nT])
reffe = dim == 2 ? [Gridap.TRI3,] : [Gridap.TET4,]
etype = [Int8(1) for k = 1:nT] # first order elements only for the moment
grid = Gridap.Geometry.UnstructuredGrid(nodes, cells, reffe, etype)
# topology
polytopes = dim == 2 ? [Gridap.ReferenceFEs.TRI,] : [Gridap.ReferenceFEs.TET,]
grid_topology = Gridap.Geometry.UnstructuredGridTopology(nodes, cells,
etype, polytopes)
# face labeling
D = num_cell_dims(grid_topology)
dim_to_face_to_label = [fill(Int32(0), np),]
for d ∈ 1:D
    z = fill(Int32(0), Gridap.ReferenceFEs.num_faces(grid_topology, d))
    push!(dim_to_face_to_label, z)
end
dim_to_gface_to_nodes = Array{Any, 1}(undef, D + 1)
dim_gface_to_entity = Array{Any, 1}(undef, D + 1)
for k = 1:(D + 1)        
    Id = findall(regionsdims .== (k - 1))
    dim_to_gface_to_nodes[k], dim_gface_to_entity[k] = if !isempty(Id)
        re = regions[Id[1]]
        gregion = [re[m, :] for m = 1:size(re, 1)]
        glabels = [Id[1] for _ = 1:size(re, 1)]
        for l = 2:length(Id)
            re = regions[Id[l]]
            for m = 1:size(re, 1)
                push!(gregion, re[m, :])
                push!(glabels, Id[l])
            end
        end
        Gridap.Arrays.Table(gregion), copy(glabels)
    else
        Gridap.Arrays.Table(Array{Array{Int64, 1}, 1}(undef, 0)), Int64[]
    end
end
# ??????
dim_to_offset = [0, 0, 0, 0]
GridapGmsh._fill_dim_to_face_to_label!(dim_to_face_to_label, grid_topology, dim_to_gface_to_nodes, dim_gface_to_entity, dim_to_offset)
tag_to_names = regionsnames
tag_to_entities = [[k,] for k = 1:length(regions)]
face_labeling = Gridap.Geometry.FaceLabeling(dim_to_face_to_label, tag_to_entities, tag_to_names)
# model
model = Gridap.Geometry.UnstructuredDiscreteModel(grid, grid_topology, face_labeling)
```

**Comment by fverdugo** [comment]
Hi @edljk ! Thanks for your interest in the project.

About the gmsh variant. is your tag boundary_1 defined on the vertices?  You can check it by printing the model with writevtk and inspect the file that ends with a _0.

About the manual variant. The work flow is to create a UnstructuredGrid and from this an UnstructuredDiscreteModel. Finally, you can add new tags to the model. Be aware that you are using private methots that can be eliminated from Gridap at any time.

**Comment by fverdugo** [comment]
There is a constructor somewhere that builds an UnstructuredDiscreteModel from an UnstructuredGrid. Use this. It will simplify things a lot.
