### ISSUE TITLE
Use BinaryBuilder.jl to get the gmsh executable

### ISSUE THREAD

**Issue by eschnett** [gridap/GridapGmsh.jl#33]
This would simplify installing `GridapGmsh.jl`.

**Comment by eschnett** [comment]
It turns out that the respective binary is already available at <https://github.com/JuliaBinaryWrappers/gmsh_jll.jl>.

**Comment by fverdugo** [comment]
Good point @eschnett!

It should be easy to add. I think it is as simple as replace the code in the `else` block

https://github.com/gridap/GridapGmsh.jl/blob/e8f525b4d9c5e996268e04d4f7ec267244762de0/deps/build.jl#L8

by something like

```julia
using gmsh_jll
GMSH_FOUND = gmsh_jll.is_available()
if GMSH_FOIUND
  gmsh_root = gmsh_jll.artifact_dir
end
```

Can you check if this works and open a PR?
