### ISSUE TITLE
Long CI times after PR #52

### ISSUE THREAD

**Issue by fverdugo** [gridap/GridapGmsh.jl#53]
After merging the suport for GridapDistributed CI times have sky-rocketed. From 6-8 mins to about 1 hour.

I cannot reproduce this long compilation times in my machine. Locally, I just get a small increase as expected since we are testing more functionality.

Can you reproduce the problem locally?

cc @oriolcg @amartinhuertas @ericneiva

**Comment by amartinhuertas** [comment]
I recalled that GridapDistirbuted was an absolute turtle with Julia 1.5. I updated the Julia version in ci to 1.7 and the problem disappeared. https://github.com/gridap/GridapGmsh.jl/pull/54
