### ISSUE TITLE
Precompilation of GridapGmsh crashes with current dev version of Gridap

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/GridapGmsh.jl#67]
To not forget ...

Once we release the current dev version of Gridap with the following PR:

https://github.com/gridap/Gridap.jl/pull/892/files

precompilation of GridapGmsh will crash as we typo fixed one function name, namely, `max_cells_arround_vertex`, that GridapGmsh uses ...

**Comment by JordiManyer** [comment]
I've created [a branch](https://github.com/gridap/GridapGmsh.jl/tree/fix-gridap-typo) attached to `Gridap#master` with the necessary fixes, for anyone who needs to use `GridapGmsh` together with the latest Gridap changes. We can merge it once we release Gridap 0.17.18.

**Comment by amartinhuertas** [comment]
Thanks a lot!
