### ISSUE TITLE
GridapGmsh fails to compile

### ISSUE THREAD

**Issue by smarras79** [gridap/GridapGmsh.jl#73]
Hi, while I didn't have issues in the past, I am having problems compiling GridapGmsh with the error listed below. 
Notice that this is a clean installation using Julia 1.8.5 on a Mac with no pre-existing ~/.julia directory.

`    Building GridapGmsh → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/5e3fb42c7dfab8f6f421bb13be2f76014ed9f9af/build.log`
Precompiling project...
  ✗ GridapGmsh
  22 dependencies successfully precompiled in 15 seconds. 94 already precompiled.
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

(tmp) pkg> precompile
Precompiling project...
  ✗ GridapGmsh
  0 dependencies successfully precompiled in 9 seconds. 116 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

GridapGmsh [3025c34a-b394-11e9-2a55-3fee550c04c8]

Failed to precompile GridapGmsh [3025c34a-b394-11e9-2a55-3fee550c04c8] to /Users/simone/.julia/compiled/v1.8/GridapGmsh/jl_8Yd2to.
ERROR: LoadError: UndefVarError: max_cells_arround_vertex not defined
Stacktrace:
 [1] include
   @ ./Base.jl:419 [inlined]
 [2] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [3] top-level scope
   @ stdin:1
in expression starting at /Users/simone/.julia/packages/GridapGmsh/Q8ZwW/src/GridapGmsh.jl:1
in expression starting at stdin:1

(tmp) pkg> 
`
@fverdugo

**Comment by amartinhuertas** [comment]
Hi @smarras79,

I would say that the issue is that you are using gridapgmsh 0.6 with the latest release of gridap, namely 0.17.18. Am I correct ? (I could not see the versions in your error message) in such a case you should use gridapgmsh 0.7 along with gridap 0.17.18. 

Hope this helps.

**Comment by smarras79** [comment]
Thank you @amartinhuertas that solved it.

All the best,

**Comment by amartinhuertas** [comment]
> Thank you @amartinhuertas that solved it.

Welcome! We have recently release a bunch of new version of several packages in the Gridap ecosystem. Let me know if you have any other issues.
